// Pass configuration data to LOG module

LOG.LOG_TO_CONSOLE   = LOG_TO_CONSOLE;
LOG.LOG_LEVEL        = LOG_LEVEL;
LOG.LOG_ENTRY_EXIT   = LOG_ENTRY_EXIT;
LOG.FILE_PATH_LOG    = FILE_PATH_LOG;

ATTRIBUTES_FOR_STYLE_COMPARISONS.Paragraph = ATTRIBUTES_FOR_STYLE_COMPARISONS.ParagraphStyle;
ATTRIBUTES_FOR_STYLE_COMPARISONS.TextStyleRange = ATTRIBUTES_FOR_STYLE_COMPARISONS.CharacterStyle;
ATTRIBUTES_FOR_STYLE_COMPARISONS.Font = {
	fullName: 1
};
ATTRIBUTES_FOR_STYLE_COMPARISONS.Application = {};
ATTRIBUTES_FOR_STYLE_COMPARISONS.Events = {};
ATTRIBUTES_FOR_STYLE_COMPARISONS.EventListeners = {};
